name: CI build for connection limit
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  connection-limit-build-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    
    strategy:
      matrix:
         prog : 
          - 
           name: xdp-root
           artifact-dir: l3af_xdp_root
           aritfact-name: xdp-root-linux-artifact
          - 
           name: tc-root
           artifact-dir: l3af_tc_root
           aritfact-name: tc-root-linux-artifact
          - 
           name: ratelimiting
           artifact-dir: l3af_ratelimiting
           aritfact-name: ratelimiting-linux-artifact
          - 
           name: connection-limit
           artifact-dir: l3af_connection_limit
           aritfact-name: connection-limit-linux-artifact
          - 
           name: traffic-mirroring
           artifact-dir: l3af_traffic_mirroring
           aritfact-name: traffic-mirroring-linux-artifact
          - 
           name: ipfix-flow-exporter
           artifact-dir: l3af_bpf_ipfix
           aritfact-name: ipfix-flow-exporter-linux-artifact


    steps:
      - name: Set env variables
        run: |
          echo "REPO=eBPF-Package-Repository" >> $GITHUB_ENV
          echo "PROG= ${{ matrix.prog.name }}" >> $GITHUB_ENV
          echo "BPF_PATH=samples/bpf" >> $GITHUB_ENV
          echo "LINUX_SRC_PATH=$GITHUB_WORKSPACE/linux" >> $GITHUB_ENV
          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
          echo "TZ=Etc/UTC" >> $GITHUB_ENV

      - name: Set up build environment
        run: |
          apt-get update
          apt-get install -y bc \
          tzdata \
          bison \
          build-essential \
          clang \
          curl \
          exuberant-ctags \
          flex \
          gcc-multilib \
          git \
          gnutls-bin \
          libc6-dev \
          libcurl4-openssl-dev \
          libelf-dev \
          libjson-c-dev \
          libncurses5-dev \
          libpcap-dev \
          libssl-dev \
          linux-headers-generic \
          linux-tools-common \
          linux-tools-generic \
          llvm \
          rsync \
          dwarves \
          zlib1g  \
          libelf1 \
          pkg-config 

      - name: Clone dependencies
        run: |
          git clone --branch v5.15 --depth 1 https://github.com/torvalds/linux.git $LINUX_SRC_PATH
          cd $LINUX_SRC_PATH
          sed -i '229a\
                  if [ "${pahole_ver}" -ge "124" ]; then\
                          extra_paholeopt="${extra_paholeopt} --skip_encoding_btf_enum64"\
                  fi' scripts/link-vmlinux.sh
          echo "CONFIG_DEBUG_INFO_BTF=y" >> .config
          echo "CONFIG_MODULES=y" >> .config
          make oldconfig
          make prepare
          yes | make -j$(nproc)
          make headers_install

      - name: Install bpftool
        run: |
          git clone --branch v7.2.0 --recurse-submodules https://github.com/libbpf/bpftool.git
          cd bpftool/src
          make
          cp bpftool /usr/local/bin/
          cd ../../
          rm -rf bpftool
          
      - name: Clone kernel function repository
        uses: actions/checkout@v2
        with:
          path: linux/${{ env.BPF_PATH }}/${{ env.REPO }}/

      - name: Generate vmlinux.h
        run: |     
          mkdir -p $LINUX_SRC_PATH/$BPF_PATH/$REPO/headers 
          bpftool btf dump file /sys/kernel/btf/vmlinux format c > $LINUX_SRC_PATH/$BPF_PATH/$REPO/headers/vmlinux.h

      - name: Build eBPF Programs
        run: |
          cd $LINUX_SRC_PATH/$BPF_PATH/$REPO/$PROG
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.prog.artifact-name }}
          path: ${{ env.LINUX_SRC_PATH }}/${{ env.BPF_PATH }}/${{ env.REPO }}/${{ env.PROG }}/${{ matrix.prog.artifact-dir }}/*

